In [1]:
import numpy as np
import sys
sys.path.append('/home/hardik/Desktop/Research/Adversary-CBF')
from utils.mvgp import MVGP

/home/hardik/Desktop/Research/Adversary-CBF/venv/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
train_x = np.linspace(1,10,100).reshape(1,-1)

In [3]:
train_y1 = np.cos(train_x)
train_y2 = np.sin(train_x)
omega = np.array([ [1.0, 0.5],[0.5, 1.0] ])
l = 0.4
sigma = 1.0

In [4]:
train_y = np.append( train_y1, train_y2, axis=0 )

In [5]:
train_y.shape

(2, 100)

In [6]:
gp = MVGP( X = train_x.T, Y = train_y.T, omega = omega, sigma = sigma, l = l, noise = 0.05, horizon=300 )

In [11]:
ys = []
for i in range(train_x.shape[1]):
    y = gp.predict( train_x[:,i].T )
    print(y)
    if ys == []:
        ys = np.copy(y)
    else:
        ys = np.append( ys, y, axis=0 )

(0.0, array([[1.05 , 0.525],
       [0.525, 1.05 ]]))
(0.0, array([[1.05 , 0.525],
       [0.525, 1.05 ]]))
(0.0, array([[1.05 , 0.525],
       [0.525, 1.05 ]]))
(0.0, array([[1.05 , 0.525],
       [0.525, 1.05 ]]))
(0.0, array([[1.05 , 0.525],
       [0.525, 1.05 ]]))
(0.0, array([[1.05 , 0.525],
       [0.525, 1.05 ]]))
(0.0, array([[1.05 , 0.525],
       [0.525, 1.05 ]]))
(0.0, array([[1.05 , 0.525],
       [0.525, 1.05 ]]))
(0.0, array([[1.05 , 0.525],
       [0.525, 1.05 ]]))
(0.0, array([[1.05 , 0.525],
       [0.525, 1.05 ]]))
(0.0, array([[1.05 , 0.525],
       [0.525, 1.05 ]]))
(0.0, array([[1.05 , 0.525],
       [0.525, 1.05 ]]))
(0.0, array([[1.05 , 0.525],
       [0.525, 1.05 ]]))
(0.0, array([[1.05 , 0.525],
       [0.525, 1.05 ]]))
(0.0, array([[1.05 , 0.525],
       [0.525, 1.05 ]]))
(0.0, array([[1.05 , 0.525],
       [0.525, 1.05 ]]))
(0.0, array([[1.05 , 0.525],
       [0.525, 1.05 ]]))
(0.0, array([[1.05 , 0.525],
       [0.525, 1.05 ]]))
(0.0, array([[1.05 , 0.525],

/tmp/ipykernel_11273/2433427677.py:5: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if ys == []:


In [10]:
ys.shape

(200,)

In [12]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [15]:
import torch
a = torch.tensor([1,1]).reshape(1,-1)
b = torch.tensor([2,2]).reshape(-1,1)

In [16]:
a

tensor([[1, 1]])

In [17]:
b

tensor([[2],
        [2]])

In [18]:
a @ b

tensor([[4]])

In [19]:
a * b

tensor([[2, 2],
        [2, 2]])

In [22]:
torch.matmul(b,a)

tensor([[2, 2],
        [2, 2]])

In [23]:
a**2

tensor([[1, 1]])

In [24]:
b**2

tensor([[4],
        [4]])

In [2]:
a = np.append( np.ones((300,600)), np.zeros((300,1)), axis=1)

In [3]:
a[:,-1000:][:,-1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [4]:
a.shape

(300, 601)

In [5]:
a[:,-1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [7]:
import torch
a = torch.ones((2,5))

In [9]:
b = torch.tensor([ [1,2,3,4,5] ])

In [10]:
a * b

tensor([[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.]])